server {
  listen 80;
  server_name 100-day-games.sytko.de _;
  root /usr/share/nginx/html;

  location ~ "^/([0-9]{3})/?$" {
    try_files /games/$1/index.html /index.html;
  }

  location ~ "^/([0-9]{3})(/.+)$" {
    try_files /games/$1$2 /games/$1/index.html /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
