server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location = / {
    return 302 /100-days-games/;
  }

  location /100-days-games/ {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /index.html;
  }
}
