const canvas=document.getElementById('gameCanvas');const ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const symbols=['moon','crane','pine','sakura','river','cloud'];const seasons=['blue','red','gold','violet'];
let cards=[],selected=0,targetId=0,cue={},state='menu',score=0,best=Number(localStorage.getItem('day043Best')||0),hearts=3,lantern=100,rivalCards=0,combo=1,focus=0,elapsed=0,setIndex=0,setProgress=0,rivalReach=18,muted=false,scanPulse=0,focusActive=false,locked=null,victory=false,last=performance.now(),message='The reader lifts the first cue. Scan the cards, mark a likely match, then sweep cleanly.';
let audio={ctx:null,enabled:false};window.__day043Audio=audio;
function mulberry(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}let rnd=mulberry(43043);
function resize(){const r=canvas.getBoundingClientRect();canvas.width=Math.max(600,Math.floor(r.width*devicePixelRatio));canvas.height=Math.max(380,Math.floor(r.height*devicePixelRatio));ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}addEventListener('resize',resize);resize();
function initAudio(){if(audio.ctx)return;try{const C=window.AudioContext||window.webkitAudioContext;audio.ctx=new C();audio.enabled=true;window.__day043Audio=audio;if(audio.ctx.state!=='running')audio.ctx.resume();tone(520,.04,'triangle',.05)}catch{audio.enabled=false}}
function tone(freq=440,dur=.08,type='sine',gain=.04){if(muted||!audio.ctx)return;const c=audio.ctx,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+dur)}
function newSet(){const counts=[10,12,16];const names=['First Moon Syllable','Crane Verse Rush','Full Lantern Match'];setProgress=0;rivalReach=18;cards=[];const n=counts[Math.min(setIndex,2)];targetId=Math.floor(rnd()*n);for(let i=0;i<n;i++){cards.push({id:i,x:.12+rnd()*.76,y:.16+rnd()*.68,rot:(rnd()-.5)*.35,symbol:symbols[Math.floor(rnd()*symbols.length)],season:seasons[Math.floor(rnd()*seasons.length)],moon:rnd()>.45,marked:false,revealed:i<3,won:false,locked:false,shake:0})}cards[targetId].symbol=symbols[(setIndex+1)%symbols.length];cards[targetId].season=seasons[(setIndex+2)%seasons.length];cards[targetId].moon=true;cue={name:names[Math.min(setIndex,2)],symbol:cards[targetId].symbol,season:cards[targetId].season,moon:true};selected=0;locked=null;message='New mooncall: find '+cue.season+' '+cue.symbol+' with a moon mark.';updateHud()}
function start(){initAudio();state='playing';$('#menu').classList.add('hidden');score=0;hearts=3;lantern=100;rivalCards=0;combo=1;focus=0;elapsed=0;setIndex=0;victory=false;newSet();tone(660,.08,'triangle')}
function update(dt){if(state!=='playing')return;elapsed+=dt;lantern=Math.max(0,lantern-dt*(setIndex>=2?3.6:2.4));rivalReach+=dt*(setIndex>=2?11:7.5)*(locked===targetId ? 0.55 : 1);scanPulse=Math.max(0,scanPulse-dt);if(rivalReach>=100){rivalCards++;combo=1;hearts=Math.max(0,hearts-1);message='Rival hand won that card. Guard the red lane or sweep sooner.';tone(180,.12,'sawtooth',.035);nextCue()}if(lantern<=0||hearts<=0)end(false);updateHud()}
function nextCue(){if(setProgress>=3){setIndex++;score+=980;focus=Math.min(100,focus+30);hearts=Math.min(3,hearts+1);if(setIndex>=3&&score>=5700&&!victory){victory=true;$('#victoryBanner').classList.remove('hidden');setTimeout(()=>$('#victoryBanner').classList.add('hidden'),3200);score+=3300;tone(880,.2,'triangle',.06)}newSet();return}const open=cards.filter(c=>!c.won);targetId=open[Math.floor(rnd()*open.length)]?.id??0;cue={name:['First Moon Syllable','Crane Verse Rush','Full Lantern Match'][Math.min(setIndex,2)],symbol:cards[targetId].symbol,season:cards[targetId].season,moon:cards[targetId].moon};rivalReach=12+setIndex*4;locked=null;focusActive=false;message='Next cue: '+cue.season+' '+cue.symbol+(cue.moon?' with moon mark.':'.');tone(420,.05,'triangle')}
function cardMatch(c){return (c.symbol===cue.symbol)+(c.season===cue.season)+(c.moon===cue.moon)}
function action(a){if(a==='resume'){state='playing';$('#pauseOverlay').classList.add('hidden');return}if(a==='restart'){start();$('#pauseOverlay').classList.add('hidden');$('#resultOverlay').classList.add('hidden');return}if(a==='audio'){initAudio();muted=!muted;$$('[data-action="audio"]').forEach(b=>b.textContent='Audio: '+(muted?'Off':'On'));message=muted?'Audio muted; visual cues remain active.':'Audio on after user gesture.';return}if(state!=='playing'&&a!=='pause')return;initAudio();const c=cards[selected];if(a==='prev')selected=(selected-1+cards.length)%cards.length;if(a==='next')selected=(selected+1)%cards.length;if(a==='scan'){scanPulse=1.2;cards.forEach(card=>{if(Math.hypot(card.x-c.x,card.y-c.y)<.32)card.revealed=true});focus=Math.min(100,focus+4);message='Scan Fan reveals nearby traits and confidence rings.';tone(700,.07,'triangle')}if(a==='mark'){c.marked=!c.marked;message=c.marked?'Memory Mark pinned this card.':'Memory Mark removed.';tone(560,.06,'sine')}if(a==='lock'){locked=selected;cards.forEach(x=>x.locked=false);c.locked=true;message=cardMatch(c)>=2?'Lock Card slows the rival while confidence is high.':'Wrong-looking lock: combo is fragile.';if(cardMatch(c)<2){combo=1;lantern=Math.max(0,lantern-4)}tone(500,.07,'square',.025)}if(a==='guard'){rivalReach=Math.max(0,rivalReach-24);focus=Math.min(100,focus+6);message='Guard Rival blocks the red warning lane.';tone(240,.08,'square')}if(a==='shuffle'){cards.forEach(card=>{if(Math.hypot(card.x-c.x,card.y-c.y)<.25&&!card.locked){card.x=.12+rnd()*.76;card.y=.16+rnd()*.68;card.rot=(rnd()-.5)*.5}});lantern=Math.max(0,lantern-5);message='Reshuffle Fan exposes a cluster but spends lantern time.';tone(620,.09,'triangle')}if(a==='focus'){if(focus>=50){focusActive=!focusActive;focus-=18;message='Mooncall Focus previews likely targets, decoys, and rival paths.';tone(840,.13,'sine')}else message='Mooncall Focus needs more charge.'}if(a==='sweep'){sweep(c)}if(a==='pause'){state='paused';$('#pauseOverlay').classList.remove('hidden')}updateHud()}
function sweep(c){c.shake=.4;if(c.id===targetId){c.won=true;setProgress++;score+=Math.round((260+(locked===c.id?320:0)+(c.marked?180:0))*combo);combo=Math.min(5,+(combo+.25).toFixed(2));focus=Math.min(100,focus+18);message='Correct sweep! Paper bell rings and the poem chain advances.';tone(760,.08,'triangle');if(setProgress>=3)nextCue();else nextCue()}else{hearts--;combo=1;lantern=Math.max(0,lantern-7);message='Wrong sweep: a decoy shared only '+cardMatch(c)+' cue traits.';tone(160,.14,'sawtooth',.03);if(hearts<=0)end(false)}}
function end(won){state='result';best=Math.max(best,score);localStorage.setItem('day043Best',String(best));$('#resultTitle').textContent=won?'Mooncall Victory':'Results';$('#resultText').textContent=`Final score ${score}. Set ${setIndex+1}, rival won ${rivalCards}, combo ${combo.toFixed(1)}x. ${victory?'Karuta Mooncall Victory achieved.':'Try scanning and marking before sweeping.'}`;$('#resultOverlay').classList.remove('hidden')}
function updateHud(){$('#score').textContent=score;$('#best').textContent=best;$('#hearts').textContent='♥'.repeat(hearts)+'♡'.repeat(3-hearts);$('#lantern').textContent=Math.round(lantern)+'%';$('#rivalCards').textContent=rivalCards;$('#combo').textContent=combo.toFixed(1)+'x';$('#activeCard').textContent=(selected+1)+'/'+cards.length;$('#cueTrait').textContent=cue.season||'moon';$('#windowHud').textContent=rivalReach<55?'wide':rivalReach<82?'tight':'red';$('#risk').textContent=rivalReach<55?'low':rivalReach<82?'warn':'high';$('#focus').textContent=Math.round(focus)+'%';$('#time').textContent=Math.floor(elapsed/60)+':'+String(Math.floor(elapsed%60)).padStart(2,'0');$('#setName').innerHTML=(cue.name||'First Moon Syllable')+' <span id="setProgress">'+setProgress+'/3</span>';$('#cueText').textContent=`Find ${cue.season||'blue'} ${cue.symbol||'moon'} ${cue.moon?'with moon mark':'without moon'} before the rival hand reaches it.`;$('#rivalReach').value=rivalReach;$('#rivalReachLabel').textContent=Math.round(rivalReach)+'%';$('#chainMeter').value=setProgress;$('#chainLabel').textContent=setProgress+'/3';$('#helperText').textContent=message}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.scale(canvas.width/(w*devicePixelRatio),canvas.height/(h*devicePixelRatio));ctx.restore();const sx=canvas.width/devicePixelRatio/w,sy=canvas.height/devicePixelRatio/h;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const grad=ctx.createLinearGradient(0,0,w,h);grad.addColorStop(0,'#10294a');grad.addColorStop(1,'#120916');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.22;ctx.drawImage(pieceImg,0,0,w*.35,w*.35);ctx.globalAlpha=1;ctx.strokeStyle='rgba(242,196,91,.25)';ctx.lineWidth=3;roundRect(18,18,w-36,h-36,18);ctx.stroke();drawRival(w,h);cards.forEach((c,i)=>drawCard(c,i,w,h));if(focusActive)drawFocus(w,h);requestAnimationFrame(draw)}
function drawCard(c,i,w,h){if(c.won)return;const x=c.x*w,y=c.y*h,cw=Math.max(52,Math.min(82,w*.08)),ch=cw*1.35;ctx.save();ctx.translate(x,y);ctx.rotate(c.rot+(c.shake?Math.sin(performance.now()/45)*.04:0));c.shake=Math.max(0,c.shake-.02);const match=cardMatch(c);ctx.shadowColor=i===selected?'#ffe37a':(focusActive&&match>=2?'#8ff1ca':'rgba(0,0,0,.5)');ctx.shadowBlur=i===selected?24:(focusActive&&match>=2?18:8);ctx.fillStyle=c.locked?'#fff0ad':'#fff7d8';ctx.strokeStyle=i===selected?'#ffe37a':(c.marked?'#ff7272':'#6b371d');ctx.lineWidth=i===selected?4:2;roundRect(-cw/2,-ch/2,cw,ch,8);ctx.fill();ctx.stroke();ctx.fillStyle=seasonColor(c.season);ctx.beginPath();ctx.arc(0,-ch*.18,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#5b351c';ctx.font='800 13px system-ui';ctx.textAlign='center';ctx.fillText(c.symbol.slice(0,2).toUpperCase(),0,5);if(c.moon){ctx.fillStyle='#d9a633';ctx.beginPath();ctx.arc(12,20,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff7d8';ctx.beginPath();ctx.arc(16,17,8,0,Math.PI*2);ctx.fill()}if(c.marked){ctx.fillStyle='#bd2c42';ctx.beginPath();ctx.moveTo(-cw/2+9,-ch/2-8);ctx.lineTo(-cw/2+18,-ch/2+8);ctx.lineTo(-cw/2,-ch/2+8);ctx.closePath();ctx.fill()}if(scanPulse>0||c.revealed||focusActive){ctx.fillStyle='rgba(15,20,30,.78)';ctx.fillRect(-cw/2+5,ch/2-20,cw-10,15);ctx.fillStyle='#ffe6a5';ctx.font='700 10px system-ui';ctx.fillText(match+'/3',0,ch/2-9)}ctx.restore()}
function drawRival(w,h){const t=rivalReach/100;const ty=h*(.18+.68*((targetId%5)/5));ctx.strokeStyle=rivalReach>80?'rgba(255,95,95,.9)':'rgba(255,215,125,.45)';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(w+30,ty);ctx.lineTo(w-(w*t*.78),ty);ctx.stroke();ctx.fillStyle='rgba(20,9,22,.82)';ctx.beginPath();ctx.ellipse(w-(w*t*.78),ty,22,11,0,0,Math.PI*2);ctx.fill()}
function drawFocus(w,h){cards.forEach(c=>{if(c.won)return;const m=cardMatch(c);if(m>=2){ctx.strokeStyle=m===3?'#8ff1ca':'#ffe076';ctx.lineWidth=3;ctx.beginPath();ctx.arc(c.x*w,c.y*h,50,0,Math.PI*2);ctx.stroke()}})}
function roundRect(x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath()}
function seasonColor(s){return {blue:'#5ab7ff',red:'#e6534f',gold:'#e0ac38',violet:'#9e66ff'}[s]||'#ddd'}
const pieceImg=new Image();pieceImg.src='./assets/karuta-pieces.png';
canvas.addEventListener('pointerdown',e=>{if(state!=='playing')return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;let bestI=0,bestD=99;cards.forEach((c,i)=>{if(c.won)return;const d=Math.hypot(c.x-x,c.y-y);if(d<bestD){bestD=d;bestI=i}});selected=bestI;message='Selected card '+(selected+1)+'. Traits match '+cardMatch(cards[selected])+'/3.';updateHud()});
canvas.addEventListener('pointerup',e=>{if(state==='playing'&&e.pointerType==='touch'&&cards[selected]&&Math.random()<0.01){} });
$$('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action)));$('#startButton').addEventListener('click',start);addEventListener('keydown',e=>{const map={ArrowLeft:'prev',a:'prev',ArrowRight:'next',d:'next',s:'scan',m:'mark',l:'lock',g:'guard',f:'shuffle',c:'focus',Shift:'focus',' ':'sweep',Enter:'sweep',p:'pause',r:'restart'};if(map[e.key]){e.preventDefault();action(map[e.key])}});
newSet();updateHud();draw();setInterval(()=>{const now=performance.now(),dt=(now-last)/1000;last=now;update(dt)},250);
