(() => {
  const $ = (id) => document.getElementById(id);
  const q = (sel) => document.querySelector(sel);
  const qa = (sel) => [...document.querySelectorAll(sel)];
  const canvas = $('gameCanvas');
  const ctx = canvas.getContext('2d');
  const W = canvas.width, H = canvas.height, C = W / 2;
  const ui = {
    score: $('scoreOut'), best: $('bestOut'), hearts: $('heartsOut'), temp: $('tempOut'), bitter: $('bitterOut'), combo: $('comboOut'), orbit: $('orbitOut'), time: $('timeOut'),
    foam: $('foamOut'), align: $('alignOut'), band: $('bandOut'), clump: $('clumpOut'), focus: $('focusOut'), commission: $('commissionName'), text: $('commissionText'), helper: $('helperText'), status: $('statusOut'),
    title: $('titleOverlay'), pause: $('pauseOverlay'), result: $('resultOverlay'), results: $('resultsText'), banner: $('perfectBanner'), menuBest: $('menuBest'), menuPerfect: $('menuPerfect'), mute: $('muteBtn'), pauseMute: $('pauseMuteBtn')
  };
  const bestKey = 'day027-haru-best';
  const perfectKey = 'day027-haru-perfect-time';
  const commissions = [
    { name: 'First Spring Froth', text: 'Build 70% fine foam, trace a broad spring crest, skim clumps, serve at 62-72°C.', foam: 70, align: 62, temp: [62, 72], bitter: 36, clumps: 3 },
    { name: 'Sakura Guest Bowl', text: 'Fold sakura petals into a three-leaf crest, keep bitterness under 32%, serve warm.', foam: 78, align: 74, temp: [61, 69], bitter: 32, clumps: 2 },
    { name: 'Garden Ceremony Crest', text: 'Lock the five-point garden crest with Tea Focus, no clumps, and a narrow serving band.', foam: 84, align: 84, temp: [63, 67], bitter: 28, clumps: 0 }
  ];
  const state = { running: false, paused: false, muted: false, won: false, score: 0, best: Number(localStorage.getItem(bestKey) || 0), hearts: 3, temp: 68, bitter: 0, combo: 1, orbit: 0.54, focus: 0, focusTimer: 0, foam: 0, align: 0, chapter: 0, start: 0, elapsed: 0, angle: -Math.PI / 2, velocity: 0, dir: 1, clumps: [], bubbles: [], petals: [], sparks: [], smooth: 0, served: 0, fanCd: 0, drag: false };
  let audio;
  function initAudio() { if (audio) return; const AC = window.AudioContext || window.webkitAudioContext; if (!AC) { window.__day027Audio = { enabled: false, ctx: null }; return; } audio = { ctx: new AC(), enabled: true }; window.__day027Audio = audio; }
  function sound(f = 440, d = .08, type = 'sine', g = .035) { if (!audio || state.muted) return; const a = audio.ctx, o = a.createOscillator(), gain = a.createGain(); o.type = type; o.frequency.value = f; gain.gain.value = .0001; o.connect(gain); gain.connect(a.destination); gain.gain.exponentialRampToValueAtTime(g, a.currentTime + .01); gain.gain.exponentialRampToValueAtTime(.0001, a.currentTime + d); o.start(); o.stop(a.currentTime + d + .02); }
  function pos(a, r) { return { x: C + Math.cos(a) * r, y: C + Math.sin(a) * r * .72 }; }
  function setStatus(t) { ui.status.textContent = t; ui.helper.textContent = t; }
  function spawnBubble(a = state.angle, r = 95 + state.orbit * 210, fine = .7) { state.bubbles.push({ a: a + (Math.random() - .5) * .45, r: r + (Math.random() - .5) * 38, s: 5 + Math.random() * 11, fine, life: 8 + Math.random() * 8 }); }
  function spawnClump() { state.clumps.push({ a: Math.random() * Math.PI * 2, r: 88 + Math.random() * 165, s: 14 + Math.random() * 13 }); }
  function spawnPetal() { state.petals.push({ a: Math.random() * Math.PI * 2, r: 100 + Math.random() * 180, s: 9 + Math.random() * 9, drift: (Math.random() - .5) * .008 }); }
  function targets() { const n = state.chapter === 0 ? 3 : state.chapter === 1 ? 4 : 5; return Array.from({ length: n }, (_, i) => ({ a: i * Math.PI * 2 / n - Math.PI / 2 + Math.sin(state.elapsed * .00045) * .08, r: 120 + (i % 2) * 38 })); }
  function setCommission() { const c = commissions[state.chapter]; ui.commission.textContent = c.name; ui.text.textContent = c.text; ui.band.textContent = `${c.temp[0]}-${c.temp[1]}°C`; }
  function start() { initAudio(); audio?.ctx.resume?.(); Object.assign(state, { running: true, paused: false, won: false, score: 0, hearts: 3, temp: 68, bitter: 0, combo: 1, orbit: .54, focus: 0, focusTimer: 0, foam: 8, align: 0, chapter: 0, start: performance.now(), elapsed: 0, angle: -Math.PI/2, velocity: 0, dir: 1, clumps: [], bubbles: [], petals: [], sparks: [], smooth: 0, served: 0, fanCd: 0 }); for (let i = 0; i < 24; i++) spawnBubble(Math.random()*Math.PI*2, 90 + Math.random()*145, .45); for (let i = 0; i < 2; i++) spawnClump(); for (let i = 0; i < 4; i++) spawnPetal(); setCommission(); ui.title.classList.remove('show'); ui.pause.classList.remove('show'); ui.result.classList.remove('show'); setStatus('Whisk smooth circles. Build foam, skim clumps, serve inside the temperature band.'); sound(523,.12,'triangle'); }
  function whisk(d, p = 1) { if (!state.running || state.paused) return; state.dir = d; state.velocity += d * .07 * p; const q = Math.max(.25, 1 - Math.abs(Math.abs(state.velocity) - .11) * 4.2); state.temp += .026 * p; state.bitter += Math.max(0, Math.abs(state.velocity) - .1) * 4.8; state.foam = Math.min(100, state.foam + .34 * q); state.focus = Math.min(100, state.focus + .28 * q); if (q > .72) state.smooth++; if (Math.random() < .55) spawnBubble(state.angle, 95 + state.orbit * 210, q); state.score += Math.round(10 * q * state.combo); sound(310 + q * 250, .035, 'sine', .011); }
  function action(name) { if (name === 'restart') return start(); if (name === 'resume') return pause(false); if (name === 'pause') return pause(true); if (!state.running || state.paused) return; if (name === 'tighten') { state.orbit = Math.max(.22, state.orbit - .08); setStatus('Tighter orbit builds dense fine foam.'); }
    if (name === 'widen') { state.orbit = Math.min(.88, state.orbit + .08); setStatus('Wider orbit steers foam toward crest arcs.'); }
    if (name === 'powder') { state.foam = Math.min(100, state.foam + 9); state.bitter = Math.min(100, state.bitter + 2); spawnClump(); for (let i=0;i<5;i++) spawnBubble(state.angle, 125 + Math.random()*90, .65); setStatus('Powder blooms foam and creates clumps to skim.'); sound(180,.08,'square'); }
    if (name === 'skim') { const w = pos(state.angle, 95 + state.orbit * 210); let hit = 0; state.clumps = state.clumps.filter(c => { const p = pos(c.a,c.r); const ok = Math.hypot(p.x-w.x,p.y-w.y) < 62; if (ok) hit++; return !ok; }); if (hit) { state.score += hit*130; state.bitter = Math.max(0, state.bitter - hit*5); state.focus = Math.min(100, state.focus + hit*10); setStatus(`Clean skim removed ${hit} clump${hit>1?'s':''}.`); sound(650,.09,'triangle'); } else { setStatus('Move the whisk near a green clump before skimming.'); sound(130,.1,'sawtooth'); } }
    if (name === 'rest') { state.velocity *= .35; state.bitter = Math.max(0,state.bitter-1.8); state.align = Math.min(100,state.align+4); setStatus('Rest Whisk lets foam settle into the crest.'); sound(260,.12,'sine'); }
    if (name === 'fan') { if (state.fanCd > 0) return; state.fanCd = 3; state.temp = Math.max(54,state.temp-4); state.align = Math.max(0,state.align-4); for(let i=0;i<16;i++) state.sparks.push({x:160+Math.random()*400,y:220+Math.random()*120,vx:(Math.random()-.5)*3,vy:-1-Math.random()*2,life:1,c:'#e8fff2'}); setStatus('Steam Fan cools the bowl but scatters a little foam.'); sound(220,.16,'sine'); }
    if (name === 'focus') { if (state.focus < 100) return; state.focus = 0; state.focusTimer = 4; setStatus('Tea Focus slows foam drift and brightens the crest guide.'); sound(880,.16,'triangle'); setTimeout(()=>sound(1180,.18,'sine'),90); }
    if (name === 'serve') serve(); }
  function serve() { const c=commissions[state.chapter]; const ok = state.foam>=c.foam && state.align>=c.align && state.temp>=c.temp[0] && state.temp<=c.temp[1] && state.bitter<=c.bitter && state.clumps.length<=c.clumps; if (ok) { state.score += 760 + Math.round(state.align*8) + (state.clumps.length===0?900:0); state.served++; state.chapter++; state.combo = Math.min(4,state.combo+.35); state.hearts=Math.min(3,state.hearts+1); sound(660,.15,'triangle'); setTimeout(()=>sound(990,.18,'triangle'),100); if (state.chapter >= 3 && state.score >= 4100) return win(); if (state.chapter >= 3) state.chapter = 2; state.foam = 28; state.align = 18; state.temp = 68; state.bitter = Math.max(0,state.bitter-8); state.clumps=[]; spawnClump(); setCommission(); setStatus('Clean serve. A new tea commission is ready.'); } else { state.hearts--; state.combo = 1; state.bitter = Math.min(100,state.bitter+12); setStatus('Serve not ready: check foam, crest, temperature, bitterness, and clumps.'); sound(120,.16,'sawtooth'); if (state.hearts <= 0) end('Ceremony hearts cracked before the tea was ready.'); } }
  function win() { state.won = true; state.score += 1700; ui.banner.classList.add('show'); setTimeout(()=>ui.banner.classList.remove('show'),3600); end('Haru Perfect Usucha! The spring foam crest blossoms into sakura.'); }
  function end(msg) { state.running=false; state.best = Math.max(state.best,state.score); localStorage.setItem(bestKey,String(state.best)); if (state.won) localStorage.setItem(perfectKey,String(Math.round(state.elapsed/1000))); ui.results.innerHTML = `<span>${msg}</span><span>Score ${state.score} · served ${state.served} bowls · smooth strokes ${state.smooth}</span><span>Final foam ${Math.round(state.foam)}% · crest ${Math.round(state.align)}% · bitterness ${Math.round(state.bitter)}%</span>`; ui.result.classList.add('show'); }
  function pause(v = !state.paused) { if (!state.running) return; state.paused = v; ui.pause.classList.toggle('show',state.paused); }
  function update(dt) { if (!state.running || state.paused) return; state.elapsed = performance.now() - state.start; const slow = state.focusTimer > 0 ? .38 : 1; state.angle += state.velocity * dt * slow * 60; state.velocity *= Math.pow(.88,dt*60); state.temp = Math.max(52,Math.min(82,state.temp + (-.55 + Math.abs(state.velocity)*3.4)*dt)); state.bitter = Math.min(100,Math.max(0,state.bitter - .45*dt + Math.max(0,Math.abs(state.velocity)-.14)*18*dt)); state.fanCd=Math.max(0,state.fanCd-dt); state.focusTimer=Math.max(0,state.focusTimer-dt); if (Math.random()<.006 && state.clumps.length<5) spawnClump(); if (Math.random()<.006 && state.petals.length<6) spawnPetal(); const ts=targets(); let near=0; for(const b of state.bubbles){ b.a += .012*state.dir*dt*60*slow; b.r += Math.sin(state.elapsed*.001+b.a)*.06; b.life -= dt*.035; if (ts.some(t => Math.abs(Math.atan2(Math.sin(b.a-t.a),Math.cos(b.a-t.a)))<.23 && Math.abs(b.r-t.r)<44)) near += b.fine; } state.bubbles=state.bubbles.filter(b=>b.life>0&&b.r>45&&b.r<300).slice(-190); for(const p of state.petals) p.a += p.drift*dt*60; for(const s of state.sparks){s.x+=s.vx*dt*60;s.y+=s.vy*dt*60;s.life-=dt;} state.sparks=state.sparks.filter(s=>s.life>0); state.foam=Math.max(0,Math.min(100,state.foam-.6*dt+state.bubbles.length*.0015)); const target=Math.min(100,near*5.4+state.foam*.2-state.clumps.length*5-Math.abs(state.temp-66)*1.15); state.align += (target-state.align)*(state.focusTimer>0?.055:.028); if (state.bitter>=100) end('Bitterness overwhelmed the bowl.'); }
  function draw() { ctx.clearRect(0,0,W,H); const grad=ctx.createRadialGradient(C,C,20,C,C,350); grad.addColorStop(0,'#dff5a1'); grad.addColorStop(.6,'#79b244'); grad.addColorStop(1,'#fff6df'); ctx.fillStyle=grad; ctx.fillRect(0,0,W,H); ctx.save(); ctx.translate(C,C); ctx.scale(1,.72); ctx.fillStyle='#fff8e8'; ctx.beginPath(); ctx.ellipse(0,0,330,330,0,0,Math.PI*2); ctx.fill(); ctx.lineWidth=22; ctx.strokeStyle='#d7b374'; ctx.stroke(); ctx.fillStyle='#75ad31'; ctx.beginPath(); ctx.ellipse(0,0,292,292,0,0,Math.PI*2); ctx.fill(); ctx.restore(); for(const t of targets()){ const p=pos(t.a,t.r); ctx.beginPath(); ctx.arc(p.x,p.y,state.focusTimer>0?36:28,0,Math.PI*2); ctx.strokeStyle=state.focusTimer>0?'rgba(255,245,170,.96)':'rgba(255,255,255,.58)'; ctx.lineWidth=state.focusTimer>0?6:3; ctx.setLineDash([8,9]); ctx.stroke(); ctx.setLineDash([]); } for(const p of state.petals){ const xy=pos(p.a,p.r); ctx.fillStyle='rgba(235,137,164,.82)'; ctx.beginPath(); ctx.ellipse(xy.x,xy.y,p.s,p.s*.55,p.a,0,Math.PI*2); ctx.fill(); } for(const b of state.bubbles){ const p=pos(b.a,b.r); ctx.fillStyle=`rgba(244,255,208,${Math.min(.9,b.life/8)})`; ctx.beginPath(); ctx.arc(p.x,p.y,b.s,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='rgba(255,255,255,.58)'; ctx.stroke(); } for(const c of state.clumps){ const p=pos(c.a,c.r); ctx.fillStyle='#3f6c21'; ctx.beginPath(); ctx.arc(p.x,p.y,c.s,0,Math.PI*2); ctx.fill(); ctx.fillStyle='rgba(184,220,92,.75)'; ctx.beginPath(); ctx.arc(p.x-5,p.y-4,c.s*.35,0,Math.PI*2); ctx.fill(); } const w=pos(state.angle,95+state.orbit*210); ctx.strokeStyle='#9a6428'; ctx.lineWidth=8; ctx.lineCap='round'; ctx.beginPath(); ctx.moveTo(w.x,w.y); ctx.lineTo(w.x+Math.cos(state.angle+Math.PI)*62,w.y+Math.sin(state.angle+Math.PI)*46); ctx.stroke(); ctx.fillStyle='#e1b35d'; ctx.beginPath(); ctx.ellipse(w.x,w.y,20,34,state.angle,0,Math.PI*2); ctx.fill(); ctx.strokeStyle='rgba(255,255,255,.7)'; ctx.lineWidth=2; ctx.beginPath(); ctx.arc(C,C,95+state.orbit*210,0,Math.PI*2); ctx.stroke(); for(const s of state.sparks){ctx.globalAlpha=Math.max(0,s.life);ctx.fillStyle=s.c;ctx.beginPath();ctx.arc(s.x,s.y,3,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;} }
  function render() { ui.score.textContent=state.score; ui.best.textContent=state.best; ui.hearts.textContent='♥'.repeat(state.hearts)+'♡'.repeat(Math.max(0,3-state.hearts)); ui.temp.textContent=`${Math.round(state.temp)}°C`; ui.bitter.textContent=`${Math.round(state.bitter)}%`; ui.combo.textContent=`×${state.combo.toFixed(1)}`; ui.orbit.textContent=`${Math.round(state.orbit*100)}%`; const sec=Math.floor(state.elapsed/1000); ui.time.textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`; const c=commissions[state.chapter]; ui.foam.textContent=`${Math.round(state.foam)}/${c.foam}%`; ui.align.textContent=`${Math.round(state.align)}%`; ui.clump.textContent=`${state.clumps.length}/${c.clumps}`; ui.focus.textContent=`${Math.round(state.focus)}%`; ui.menuBest.textContent=state.best; const pt=localStorage.getItem(perfectKey); ui.menuPerfect.textContent=pt?`${pt}s`:'—'; }
  let last=performance.now(); function loop(now){ const dt=Math.min(.05,(now-last)/1000); last=now; update(dt); draw(); render(); requestAnimationFrame(loop); } requestAnimationFrame(loop);
  $('startBtn').addEventListener('click', start); qa('[data-hold="cw"]').forEach(b=>{ b.addEventListener('pointerdown',()=>whisk(1,1.2)); b.addEventListener('click',()=>whisk(1,1)); }); qa('[data-hold="ccw"]').forEach(b=>{ b.addEventListener('pointerdown',()=>whisk(-1,1.2)); b.addEventListener('click',()=>whisk(-1,1)); }); qa('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.action))); ui.mute.addEventListener('click',()=>{ state.muted=!state.muted; ui.mute.textContent=state.muted?'🔇 Muted':'🔊 Sound'; ui.mute.setAttribute('aria-pressed',String(state.muted)); }); ui.pauseMute.addEventListener('click',()=>ui.mute.click());
  window.addEventListener('keydown',e=>{ if(e.repeat) return; const k=e.key.toLowerCase(); if(k==='e')whisk(1,1.2); if(k==='q')whisk(-1,1.2); if(k==='arrowup'||k==='w')action('tighten'); if(k==='arrowdown'||k==='s')action('widen'); if(k==='1')action('powder'); if(k==='2')action('skim'); if(k==='3')action('rest'); if(k==='4'||k==='f')action('fan'); if(k==='shift'||k==='b')action('focus'); if(k===' '||k==='enter'){e.preventDefault(); state.running?action('serve'):start();} if(k==='p')action('pause'); if(k==='r')action('restart'); });
  function pointer(e){ const r=canvas.getBoundingClientRect(); return {x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}; }
  canvas.addEventListener('pointerdown',e=>{ state.drag=true; initAudio(); canvas.setPointerCapture(e.pointerId); }); canvas.addEventListener('pointermove',e=>{ if(!state.drag||!state.running||state.paused) return; const p=pointer(e); const a=Math.atan2((p.y-C)/.72,p.x-C); const delta=Math.atan2(Math.sin(a-state.angle),Math.cos(a-state.angle)); state.angle=a; state.orbit=Math.max(.22,Math.min(.88,(Math.hypot(p.x-C,(p.y-C)/.72)-95)/210)); whisk(Math.sign(delta)||state.dir,Math.min(1.4,Math.abs(delta)*9)); }); canvas.addEventListener('pointerup',()=>{state.drag=false;});
  setCommission(); render(); draw();
})();
